### ISSUE TITLE
Order stuck with the status of "processing"

### ISSUE THREAD

**Issue by willopez** [reactioncommerce/reaction-admin#176]
## Issue Description
In the orders view, an order is displayed with the status of "processing" even though the order has been marked completed.

<img width="1121" alt="orders_issue" src="https://user-images.githubusercontent.com/486340/71933708-a813b100-3157-11ea-94c8-701cf9c4da7e.png">

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Place an order
2. Login as admin and find the order you placed
3. Fulfill the order by capturing payment and updating the fulfillment group by setting to "completed"
4. Visit orders view and see your order rendered with the status "processing"

## Possible Solution
An order's status field needs to be updated correctly when an order is completed.

**Comment by kieckhafer** [comment]
Seems like the badge on the order itself is also stuck in this state:
![Order_Details_for_order_reference__2diBsGD32H7LDwbuQ](https://user-images.githubusercontent.com/4482263/73311275-e80c0800-41da-11ea-90d2-072ed3b671dc.png)

**Comment by kieckhafer** [comment]
@aldeed @willopez I'm not entirely sure this is a bug, or at least that this isn't planned to be like this in it's current state.

When we move through the process of completing an order, we complete both `payment` and `fulfillment` workflows of the order, that's what we are seeing by the two "completed" steps in the table. However, the overall "Order" workflow is the badge that's still in processing mode.

From what I remember, we purposely left the order as uncompleted because we didn't want to tie the `Order` status to the `payment` and `fulfillment` statuses.

Do we want to revisit the `Order` status and make it completed once `payment` and `fulfillment` are completed?

**Comment by aldeed** [comment]
@kieckhafer @willopez That's correct. I'm remembering now. We did not want to assume anything about when orders should be marked completed. The API has `updateOrder` mutation, which can take `status` param. We should add a button in the admin order UI to allow them to manually mark them completed by calling that mutation.

So this isn't a bug as much as it's an unimplemented feature in admin. If you want to implement it @willopez, feel free.

**Comment by kieckhafer** [comment]
Related ticket: https://github.com/reactioncommerce/reaction/issues/5695
