### ISSUE TITLE
Implement canSeeAdminUI check

### ISSUE THREAD

**Issue by aldeed** [reactioncommerce/reaction-admin#192]
Currently the admin UI always shows but for non-admins, data will be missing and some things will be broken due to API authorization checks.

Add a global setting `canSeeAdminUI` in the API, and in Reaction Admin:
- Add a way to toggle it (boolean) from settings
- Hide the UI when it's false. Show a nice message, perhaps linking to the storefront.

**Comment by trojanh** [comment]
I would like to help fix this, after some browsing, I found 
 - [updateAppSettings](https://github.com//reactioncommerce/reaction/blob/aef626b5cf695b826be38038e0542fe7db4f5a42/src/core-services/settings/mutations/updateAppSettings.js#L17) mutation which could be used to control this value.

But since `AppSettings` doesn't have a simple schema, are we suppose directly insert the value?

**Comment by aldeed** [comment]
@trojanh Check out these docs: https://docs.reactioncommerce.com/docs/next/how-to-manage-app-settings

Specifically "Global Settings API"

This would be a global setting because the admin UI will allow managing any shop (which shops you can see and manage will eventually be controlled by a different setting).

There is not any existing API plugin that is a good fit for this setting. I recommend you create a new plugin, maybe call it "admin-ui" in the `plugins` folder, and for now it will just register this new global setting and nothing else. Eventually we plan to have other admin UI settings.

The rest of the work here would then be getting and respecting this setting in reaction-admin project, but the API changes could be merged first.

Thanks!

**Comment by aldeed** [comment]
I was not thinking straight in my above comment. `canSeeAdminUI` will need to be a per-account setting, so the global settings API won't work. I'll think about this some more and post a new plan here.
