### ISSUE TITLE
Accounts screen is blank and throws error after shop creation

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction-admin#211]
## Issue Description
After creating your first user, if you click on "Accounts" the screen is blank and it throws this error in the console:

```
TypeError: Cannot read property 'ixKfbghjg9tYLX9BZ' of undefined
    at Object.canInviteToGroup (5650109b78b2a3b0e1a28555f19526d48d064113.js?meteor_js_resource=true:959)
    at 5650109b78b2a3b0e1a28555f19526d48d064113.js?meteor_js_resource=true:959
    at Array.filter (<anonymous>)
    at Reaction(GroupsTableCell) (5650109b78b2a3b0e1a28555f19526d48d064113.js?meteor_js_resource=true:959)
```

## Steps to Reproduce
1. Fresh clone of platform and start
1. Create your first account/shop
1. Click on "Accounts"

### Versions
`release-3.0.0-beta.3` Hash: `cee2161c6`

**Comment by ironynet** [comment]
me too

**Comment by aldeed** [comment]
@kieckhafer Can you look into this?

**Comment by kieckhafer** [comment]
@zenweasel I think we released a newer version after this ticket was made. Can you please try with Reaction Admin 3.0.0-beta.4 release (alongside the official Reaction 3.0.0 release)?

I can look into it if it’s still an issue.

**Comment by brent-hoover** [comment]
Yes, same error with a fresh clone including beta 4

**Comment by kieckhafer** [comment]
Thanks @zenweasel, I see where the issue is coming from.

cc: @aldeed 

There seem to be a few things going on here:
1. The `Groups` publication only publishes for the current `shopId`, which no longer works with the way we have `global` groups, especially in this instance where the `reaction:legacy:accounts/invite:groups` permission is on a Global group.
1. For this particular issue, we are still using the older way to check to see if a user is allowed to add another user to a group: if they have all the group permissions, they can add another user to the group, even if they are just a normal user, as opposed to our new permissions to add to groups, where if you have the `reaction:legacy:accounts/invite:groups` permission, you can add to any group.

I think there are a few options:
1. Remove the `canInviteToGroup` helper in the Admin, and just let the API take care of the permission check on the server for now, with the option to add it back on the client admin in the future. The updates themselves use the GQL mutations already, this just seems like a client check to only show certain groups to certain users (https://github.com/reactioncommerce/reaction-admin/blob/trunk/imports/plugins/core/accounts/client/components/adminInviteForm.js#L21:L21 & https://github.com/reactioncommerce/reaction-admin/blob/trunk/imports/plugins/core/accounts/client/containers/accountsDashboardContainer.js#L72)
1. Remove the `shopId` from the `Groups` subscription, so all the groups are returned (including global). This will require some changes to the current `Reaction.hasPermission()` function as well, but I don't think it'll be too much refactoring. Since we only have one shop at the moment, this probably will be OK, but isn't the best option going forward.
1. Add a new `GlobalGroups` subscription to work in tandem with the old `Groups`, which can stay as just the current shop.

If option 1 is the solution we want to go with: https://github.com/reactioncommerce/reaction-admin/pull/214

**Comment by aldeed** [comment]
Option 1 does seem best to me.
