### ISSUE TITLE
Admin can not see store managers in his reaction-admin dashboard

### ISSUE THREAD

**Issue by hamza0200** [reactioncommerce/reaction-admin#307]
We have followed the [Reaction Development Platform](https://docs.reactioncommerce.com/docs/installation-reaction-platform) to install Reaction.

## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Please signup as [store manager](http://localhost:4080) and create at least 2-3 accounts.

## Issue Description
An admin can not see store managers in his dashboard even when store manager exists.

## Steps to Reproduce
1. Open [reaction admin](http://localhost:4080) and click register
2. Create at least 2-3 accounts
3. Login to the [reaction admin](http://localhost:4080)
4. In the left side bar click Accounts

## Possible Solution
The shop managers should be visible to Owner

## System information
We are getting this error on multiple systems:
* MAC OS Catalina
* Ubuntu 20.04 LTS

**Comment by kieckhafer** [comment]
Thanks for the reported issue, @hamza0200.

The `reaction-development-platform` repository is used to bootstrap the project and get it up and running, but issues regarding the API, Admin, Storefront, or anything outside the initial build are better suited in their respective project repositories.

I'm going to move this issue to the `reaction-admin` repo. It's possible this is an API issue, but `admin` seems like a good place to move this until it's further investigated.

**Comment by ghost** [comment]
Issue reported fixed in #276 by @loan-laux and available in the latest beta.

<img width="838" alt="Screen Shot 2020-09-04 at 21 31 26" src="https://user-images.githubusercontent.com/65664227/92245335-cf916800-eef6-11ea-9215-9b4b5ead3dd5.png">

Note to upgrade to Beta 9 API migrations may be necessary. Instructions to check for and run them: https://habd.as/post/reaction-commerce-getting-started/#check-for-api-migrations

@kieckhafer Thanks for continuing to triage. It would be helpful if users had a script they could run to report version information when reporting tickets so issues are easier to reproduce and more timeless.

**Comment by kieckhafer** [comment]
We used to have the `reaction -v` script which spit out that information. There is probably a way to generate something *if* the user is using the `reaction-development-platform`, but I don't know how feasible it would be if they were running the apps individually. Would you mind creating a ticket in the `reaction-development-platform` repo with this idea?

**Comment by balibebas** [comment]
(All set https://github.com/reactioncommerce/reaction-development-platform/issues/158)

**Comment by hamza0200** [comment]
Thank You @kieckhafer and @balibebas for updating.
I am closing the ticket now.
