### ISSUE TITLE
Regular user can login as admin

### ISSUE THREAD

**Issue by hasan-synavos** [reactioncommerce/reaction-admin#311]
We have followed the [Reaction Development Platform](https://docs.reactioncommerce.com/docs/installation-reaction-platform) to install Reaction.

## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?

## Issue Description
A user can also login to the [admin side](http://localhost:4080) by using his same login credentials and he is able to see all modules to manage products/orders/tags etc.

## Steps to Reproduce
1. Login to reaction admin using regular user credentials
2. Navigate to Products
3. Navigate to Orders 

## Possible Solution
Regular user should *not* be allowed to login to reaction admin.

## System information
We are getting this error on multiple systems:
* MAC OS Catalina
* Ubuntu 20.04 LTS

**Comment by kieckhafer** [comment]
Thanks for the reported issue, @hasan-synavos.

The `reaction-development-platform` repository is used to bootstrap the project and get it up and running, but issues regarding the API, Admin, Storefront, or anything outside the initial build are better suited in their respective project repositories.

I'm going to move this issue to the `reaction-admin` repo.

**Comment by kieckhafer** [comment]
@hasan-synavos what exactly do you mean by `regular user`?

There seems to be a theme in a few of your tickets regarding `admin` vs `regular user`, I just want to make sure we are on the same page for our discussions.

It should be noted that the first user created is always a `manager`, not a `regular user`, and this user can log in both via the example storefront, and the admin.

**Comment by ghost** [comment]
I just restored a fresh database to my local installation and attempted to reproduce. I was not able to reproduce this behavior described in OP. Here's what I did:

1. Restored a database backup created prior to primary store creation (Using [mongo-s3-backup](https://github.com/reactioncommerce/mongo-s3-backup/pull/5))
2. Attempted to register a user via Storefront [Error]
3. Navigated to Admin and was redirected to Identity to create a user [Success]
4. Opened Storefront and attempted to register a new user [Success]
5. Logged out of Admin with first user created [OK]
6. Attempted to use Admin after logging in with second user created [OK]

Attempting to use Admin with second user created via Storefront only resulted in API permissions errors and nothing in the Admin was functional. This is expected behavior given the same identity service is used for both the Storefront and Admin.

As a result, I do not believe this is a valid issue. @hasan-synavos Am I missing something?

**Comment by kieckhafer** [comment]
I am seeing this issue more of a UI feature request than an API issue. I think the API is working as expected, and the UI is working as expected considering that it is just an example UI to showcase what's possible.

It seems like what is being experienced here is something that a shop owner will need to decide how they want to proceed, and what UI they want to show non-managerial users, and build it out accordingly.

**Comment by hamza0200** [comment]
> I just restored a fresh database to my local installation and attempted to reproduce. I was not able to reproduce this behavior described in OP. Here's what I did:
> 
> 1. Restored a database backup created prior to primary store creation (Using [mongo-s3-backup](https://github.com/reactioncommerce/mongo-s3-backup/pull/5))
> 2. Attempted to register a user via Storefront [Error]
> 3. Navigated to Admin and was redirected to Identity to create a user [Success]
> 4. Opened Storefront and attempted to register a new user [Success]
> 5. Logged out of Admin with first user created [OK]
> 6. Attempted to use Admin after logging in with second user created [OK]
> 
> Attempting to use Admin with second user created via Storefront only resulted in API permissions errors and nothing in the Admin was functional. This is expected behavior given the same identity service is used for both the Storefront and Admin.
> 
> As a result, I do not believe this is a valid issue. @hasan-synavos Am I missing something?

Thank You @balibebas for this but the steps you have followed are not as per the issue which is reported by @hasan-synavos.

`This is expected behavior given the same identity service is used for both the Storefront and Admin.`

This statement is confusing as in generally, a regular user (customer) is never allowed to signin to the admin portal regardless of the API permissions. 

This is what is being reported in this ticket.

**Comment by hamza0200** [comment]
> I am seeing this issue more of a UI feature request than an API issue. I think the API is working as expected, and the UI is working as expected considering that it is just an example UI to showcase what's possible.
> 
> It seems like what is being experienced here is something that a shop owner will need to decide how they want to proceed, and what UI they want to show non-managerial users, and build it out accordingly.

Thank you @kieckhafer for your reply.

The shop manager or admin is a different user type while the customer (regular users) is a different user.

This is understandable that `shop owners can decide how they want to proceed`, so at least a regular users credentials should  not work on admin portal. 

Even if API is common but this is not a case in general when application have both admin and customer users.
Both of the users have their own portals and should be resticted to login to their own portals.

**Comment by balibebas** [comment]
Thanks for the clarification, @hamza0200. I believe there's a disconnect in expectations. I believe the expectation set in OP is that unprivileged users are rejected when they attempt to log-in. Which would be a feature given those users probably shouldn't know about/be able to access admin in the first place (e.g. via a Traefik BasicAuth rule to block access entirely). I feel the best course of action would be to put in a feature request at the below URL unless there's a demonstrable bug.

https://github.com/reactioncommerce/reaction-feature-requests

**Comment by balibebas** [comment]
Thanks for the clarification, @hamza0200. I believe there's a disconnect in expectations. The expectation set in OP—and what I believe you're sayding—is that unprivileged users are rejected when they attempt to log-in. Which would be a feature given those users probably shouldn't know about/be able to access admin in the first place (e.g. via a Traefik BasicAuth rule to block access entirely). I feel the best course of action would be to put in a feature request at the below URL unless there's a demonstrable bug.

https://github.com/reactioncommerce/reaction-feature-requests

**Comment by ghost** [comment]
Thanks for the clarification, @hamza0200. I believe there's a disconnect in expectations. The expectation set in OP—and what I believe you're suggesting—is that unprivileged users are rejected when they attempt to log-in. Which would be a feature given those users probably shouldn't know about/be able to access admin in the first place (e.g. via a Traefik BasicAuth rule to block access entirely). I feel the best course of action would be to put in a feature request at the below URL unless there's a demonstrable bug.

https://github.com/reactioncommerce/reaction-feature-requests

**Comment by janus-reith** [comment]
While no actual admin actions can be performed without the respective authorization, and as @kieckhafer outlined this is just a frontend issue, I totally agree that the expected behaviour would not be to have regular users/anyone be able to view the admin dashboard.
IMHO this could hardly be described as a requirement which is so custom that implementation would be so different per usecase - The basic expectation is pretty clear, and anyone wanting something custom won't loose the ability to customize it.

Having no default is bad, and if I recall correctly(not speaking for the core RC team), that was less of a conscious design decision, but more due to the fact that during the refactors, no general shop access authorization was defined in the api. Now with the shop multi select in place, I believe some list with shops to access per user where added to the api, and we could use that.

A quick solution would be, to as soon as the authentication flow completed and viewer info is fetched, trigger a logout if no admin authorization is present. For regular users, that would just result in some redirect where they land back on the login screen, but with the potential issue of the admin ui being visible for a second (Maybe suspense could help, could fix the i18n issues aswell)

A more complex solution which @balibebas suggested would indeed involve some proxy, although using additional authorization like basic auth seems more like a workaround solution, and I would preferrably use the actual incoming cookie instead to determine access - However, I guess this could be hard to include in a dev environment, and also with the idea in mind to have the ability to serve the admin ui as purely static soon without reliance on server computing time + simple scaling, I would prefer the former, pure frontend js approach.
