### ISSUE TITLE
No store manager signup limit

### ISSUE THREAD

**Issue by hasan-synavos** [reactioncommerce/reaction-admin#316]
We have followed the [Reaction Development Platform](https://docs.reactioncommerce.com/docs/installation-reaction-platform) to install Reaction.

## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue?

## Issue Description
On the [reaction admin](http://localhost:4080) signup page, we can register again and again and there is no restriction to stop store manager signup accounts.

## Steps to Reproduce
1. Go to reaction admin sign up page
2. Register as many user as you want

## Possible Solution
There must be a restriction on number of store manager signups.

## System information
We are getting this error on multiple systems:
* MAC OS Catalina
* Ubuntu 20.04 LTS

**Comment by kieckhafer** [comment]
@hasan-synavos I'm not fully understanding the issue here.

Are you saying that an unlimited number of users can sign up in general, and that they are all set as "managers" with full manager permissions?

Or are you saying that you want to restrict the amount of users that can be given `manager` permissions overall?

**Comment by ghost** [comment]
Unable to reproduce. Here's what I did:

1. Restored fresh database prior to store creation using [mongo-s3-backup](https://github.com/reactioncommerce/mongo-s3-backup/pull/5)
2. Navigated to Admin (localhost:4080) and was redirected to http://localhost:4100/account/enroll
3. Completed registration of admin user and was redirected to localhost:4080 (no further action taken)
4. Enrolled a second account using full URL from 2 (including challenge query param)
5. Opened Incognito window and navigated to Admin
7. Logged in with second user created
6. Attempted to give a name to the primary store

The second user enrolled did not have permissions to name/create the primary store. As a result, I believe this issue is a duplicate of #311 which I also tested and found not to be valid.

@hasan-synavos Could you please update your reproduction steps or close this ticket? Thanks!

**Comment by hamza0200** [comment]
@balibebas , @kieckhafer.

Thanks for your reply, although it is not allowing the users to perform any action but the point which @hasan-synavos trying to highlight is, when we go to admin portal and click on register, we can register as much users as we want (which it shouldn't), if it is customer portal then this is understandable that we can register as much users as we want, even if common API is used to handle the authentication and registration, but on the admin portal it should not allow for users to signup.

**Comment by kieckhafer** [comment]
@hamza0200 

The admin and storefront use the same identity service for authentication. If a user comes from the admin, they'll be redirected to the admin; if they come from the storefront, they'll be redirected to the storefront.

I still believe the solution is to customize your admin UI to not show anything to a user if they aren't a manager, or perhaps redirect a user to the storefront once they are logged in and seen to not be a manager.

Another option would be to fork the reaction-identity service, and update the logic as you'd like it to be. I believe this would be the best place to start there: https://github.com/reactioncommerce/reaction-identity/blob/trunk/server/oauthMethods.js

This project is just an example of what could be done with an admin UI, and isn't necessarily everything that can or should be done. As the authorization seems to be working as expected, by not allowing non-admin users to perform non-admin actions, this doesn't seem like a bug, and seems like a merchant preference.

**Comment by hasan-synavos** [comment]
> @hamza0200
> 
> The admin and storefront use the same identity service for authentication. If a user comes from the admin, they'll be redirected to the admin; if they come from the storefront, they'll be redirected to the storefront.
> 
> I still believe the solution is to customize your admin UI to not show anything to a user if they aren't a manager, or perhaps redirect a user to the storefront once they are logged in and seen to not be a manager.
> 
> Another option would be to fork the reaction-identity service, and update the logic as you'd like it to be. I believe this would be the best place to start there: https://github.com/reactioncommerce/reaction-identity/blob/trunk/server/oauthMethods.js
> 
> This project is just an example of what could be done with an admin UI, and isn't necessarily everything that can or should be done. As the authorization seems to be working as expected, by not allowing non-admin users to perform non-admin actions, this doesn't seem like a bug, and seems like a merchant preference.

Closing it based on the above comment.
